# Project: XyliCrackMe1
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe -D__DEBUG__
CC   = gcc.exe -D__DEBUG__
WINDRES = windres.exe
RES  = XyliCrackMe1_private.res
OBJ  = XylicrackMe1_main.o $(RES)
LINKOBJ  = XylicrackMe1_main.o $(RES)
LIBS =   -g3 
INCS =  -I"C:/Dev-Cpp/include" 
CXXINCS =  -I"C:/Dev-Cpp/lib/gcc/mingw32/3.4.2/include"  -I"C:/Dev-Cpp/include/c++/3.4.2/backward"  -I"C:/Dev-Cpp/include/c++/3.4.2/mingw32"  -I"C:/Dev-Cpp/include/c++/3.4.2"  -I"C:/Dev-Cpp/include" 
BIN  = XyliCrackMe1.exe
CXXFLAGS = $(CXXINCS)   -g3
CFLAGS = $(INCS)   -g3
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before XyliCrackMe1.exe all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o "XyliCrackMe1.exe" $(LIBS)

XylicrackMe1_main.o: XylicrackMe1_main.c
	$(CC) -c XylicrackMe1_main.c -o XylicrackMe1_main.o $(CFLAGS)

XyliCrackMe1_private.res: XyliCrackMe1_private.rc 
	$(WINDRES) -i XyliCrackMe1_private.rc --input-format=rc -o XyliCrackMe1_private.res -O coff 
